### ISSUE TITLE
Vulnerability in transient dependency reported by Snyk

### ISSUE THREAD

**Issue by antoineco** [dprotaso/go-yit#1]
Snyk reports a vulnerability in this module due to a transient dependency: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXTEXTENCODINGUNICODE-609611

It seems to come from [`onsi/gomega`](https://github.com/onsi/gomega/issues/474) which is only used in tests, but I'll send a PR to address it right away, if you want to accept it.

**Comment by dprotaso** [comment]
Yeah sure
